/*
 * Copyright 2016 Black Pepper Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.co.blackpepper.bowman;

/**
 * An exception thrown by a failure to create or navigate the proxies generated by a {@link Client}.
 * 
 * @author Ryan Pickett
 *
 */
public class ClientProxyException extends RuntimeException {
	
	private static final long serialVersionUID = 7398487411554253606L;

	public ClientProxyException(String message) {
		super(message);
	}

	public ClientProxyException(String message, Throwable cause) {
		super(message, cause);
	}
}
